
# Introduction to Numpy in Python

Numpy (Numerical Python) is a powerful library in Python that provides support for large multi-dimensional arrays and matrices, along with a vast collection of high-level mathematical functions to operate on these arrays. Numpy is widely used in scientific computing, data analysis, and machine learning.

In this notebook, we will cover:

1. Numpy Arrays
2. Array Creation Methods
3. Array Operations
4. Array Indexing & Slicing
5. Broadcasting
6. Numpy Mathematical Functions



## 1. Numpy Arrays

At the core of Numpy is the `ndarray` object, a fast and flexible container for large data sets. You can create arrays from Python lists using `np.array()`.

### Example:
```python
import numpy as np
arr = np.array([1, 2, 3, 4, 5])
print(arr)
```

Numpy arrays support element-wise operations and have many advantages over Python lists.


In [1]:

import numpy as np

# Creating a Numpy array from a Python list
arr = np.array([1, 2, 3, 4, 5])
arr


array([1, 2, 3, 4, 5])


## 2. Array Creation Methods

Numpy provides several methods for creating arrays without manually specifying all elements. Some common methods include:

- `np.zeros(shape)`: Creates an array of given shape filled with zeros.
- `np.ones(shape)`: Creates an array of given shape filled with ones.
- `np.arange(start, stop, step)`: Creates an array with values ranging from start to stop with a specified step.
- `np.linspace(start, stop, num)`: Creates an array of evenly spaced numbers over a specified interval.


```


In [2]:

# Array creation methods
zeros_array = np.zeros((3, 3))  # 3x3 matrix of zeros
ones_array = np.ones((2, 4))    # 2x4 matrix of ones
arange_array = np.arange(0, 10, 2)  # Array with step size of 2
linspace_array = np.linspace(0, 1, 5)  # 5 evenly spaced numbers from 0 to 1

zeros_array, ones_array, arange_array, linspace_array


(array([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]]),
 array([[1., 1., 1., 1.],
        [1., 1., 1., 1.]]),
 array([0, 2, 4, 6, 8]),
 array([0.  , 0.25, 0.5 , 0.75, 1.  ]))


## 3. Array Operations

Numpy arrays support element-wise operations, allowing for fast and efficient computation. This includes basic arithmetic, comparisons, and matrix operations.



In [3]:

# Array operations
arr = np.array([1, 2, 3, 4, 5])
arr2 = np.array([10, 20, 30, 40, 50])

# Element-wise addition and multiplication
sum_array = arr + arr2
mul_array = arr * arr2

# Element-wise comparison
comparison = arr > 2

# Dot product
dot_product = np.dot(arr, arr2)

sum_array, mul_array, comparison, dot_product


(array([11, 22, 33, 44, 55]),
 array([ 10,  40,  90, 160, 250]),
 array([False, False,  True,  True,  True]),
 np.int64(550))


## 4. Array Indexing & Slicing

Numpy arrays support powerful indexing and slicing capabilities, similar to Python lists. You can access individual elements or entire subarrays using slice notation.



In [4]:

# Array indexing and slicing
arr = np.array([10, 20, 30, 40, 50])

# Accessing individual elements
first_element = arr[0]
last_element = arr[-1]

# Slicing a portion of the array
sub_array = arr[1:4]  # From index 1 to 3

first_element, last_element, sub_array


(np.int64(10), np.int64(50), array([20, 30, 40]))


## 5. Broadcasting

Numpy's broadcasting feature allows arithmetic operations to be performed on arrays of different shapes. Numpy automatically adjusts the smaller array to match the larger one.

In the following case, Numpy treats the scalar (2) as an array with the same shape as arr, but with the value 2 repeated for each element.

In [5]:

# Broadcasting example
arr = np.array([1, 2, 3])
scalar = 2

# Broadcasting a scalar value
broadcasted_result = arr * scalar
broadcasted_result


array([2, 4, 6])

### 5.1 Broadcasting Between Arrays of Different Shapes

In [7]:
# 2D array (matrix) with shape (3, 3)
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# 1D array (vector) with shape (3,)
vector = np.array([1, 2, 3])

# Add the vector to each row of the matrix (broadcasting happens here)
result = matrix + vector
print(result)


[[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]



## 6. Numpy Mathematical Functions

Numpy provides a wide range of mathematical functions such as `np.mean()`, `np.sum()`, `np.sqrt()`, `np.exp()`, and many others for efficient computation.




In [6]:

# Numpy mathematical functions
arr = np.array([1, 2, 3, 4, 5])

# Calculate sum, mean, square root, exponential
arr_sum = np.sum(arr)
arr_mean = np.mean(arr)
arr_sqrt = np.sqrt(arr)
arr_exp = np.exp(arr)

arr_sum, arr_mean, arr_sqrt, arr_exp


(np.int64(15),
 np.float64(3.0),
 array([1.        , 1.41421356, 1.73205081, 2.        , 2.23606798]),
 array([  2.71828183,   7.3890561 ,  20.08553692,  54.59815003,
        148.4131591 ]))